version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: audioplayer_db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    command: -p ${DATABASE_PORT}
volumes:
  postgres:

