version: '3.9'

services:
  web:
    build: .
    image: ghcr.io/johannesrave/audioplayer
#    command: tail -F anything
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: audioplayer_db
      DATABASE_USER: db_user
      DATABASE_PASSWORD: db_password
      DATABASE_PORT: 5434
      SECRET_KEY: "4f5wb#^n1(a8@x(+d+kn56appq53nz(h(&4@#n02=h#5u#vv0o"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: audioplayer_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5434:5434"
    command: -p 5434
#    volumes:
#      - data:/var/lib/postgresql/data
#volumes:
#  data: