version: '3.9'

services:
  django:
    image: ghcr.io/johannesrave/audioplayer:deploy
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_DB: audioplayer_db
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5435"
    command: -p 5434
volumes:
  postgres: