version: '3.9'

services:
  web:
    build: .
    image: ghcr.io/johannesrave/audioplayer
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: audioplayer_db
      DATABASE_USER: db_user
      DATABASE_PASSWORD: db_password
      DATABASE_PORT: 5434
      SECRET_KEY: "django-insecure-oqb@vxu(w1a8$y@twsd@@*-jv(-0&_a09pj998t-@zu34)@$u&"
    ports:
      - "80:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: audioplayer_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5434:5434"
    command: -p 5434
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: