# Generated by Django 3.2.9 on 2021-11-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='Unbekannter Song', max_length=128)),
                ('length', models.IntegerField(editable=False, null=True)),
                ('audio_file', models.FileField(upload_to='')),
                ('artists', models.ManyToManyField(blank=True, default='Unbekannter Artist', related_name='songs', to='player.Artist')),
                ('genre', models.ForeignKey(default='Unbekanntes Genre', on_delete=django.db.models.deletion.PROTECT, to='player.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='player.Song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('artists', models.ManyToManyField(blank=True, default='Unbekannter Artist', related_name='albums', to='player.Artist')),
                ('songs', models.ManyToManyField(blank=True, related_name='songs', to='player.Song')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
