name: "Run Docker Compose in Azure Web Apps"

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

env:
  REGISTRY: ghcr.io
  FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
        with:
          ref: deploy

      - name: Log in to the Github Packages Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}
          context: .

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy as Azure multi-container webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'speel-compose'
          configuration-file: docker-compose.yml
          images: ${{ env.FULL_IMAGE_NAME }}

      - name: Wake webapp from idle to trigger docker-compose
        run: curl --connect-timeout 5 https://speel-compose.azurewebsites.net/

      - name: Azure logout
        run: az logout
